trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    cmake .;
    make;
    install stormscript build/stormscript;
    rm stormscript
  displayName: 'Build'
- script: |
    echo Running tests:;
    cd tests;
    printf "\n";

    B=0;
    for i in $( ls | grep .sts ); do
      if [[ $(echo `cat outputs/$i.txt`) = "$(echo `../build/stormscript $i`)" ]]; then
          echo $B: Test Successful;
      else
          echo Test $B failed:;
          echo expected$'\n'$(echo `cat outputs/$i.txt`)$'\n'got$'\n'$(echo `../build/stormscript $i`);
          exit 1;
      fi;
      
      B=$(($B+1));
    done;
  displayName: 'Test'