trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    cmake .;
    make;
    install stormscript build/stormscript;
    rm stormscript
  displayName: 'Build'
- script: |
    cd scripts;
    ./runtests.sh
  displayName: 'Test'