trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    cmake .;
    make;
    install stormscript build/stormscript;
    rm stormscript
  displayName: 'Build'
- script: |
    cd tests;
    for i in $(ls); do
      touch outputs/$i.txt;
      echo $(../build/stormscript $i) > outputs/$i.txt;
    done
  displayName: 'Test'