name: stormscript
version: 'v0.2.0'
summary: StormScript is an easy to use, open-source scripting language 
description: |
  StormScript is an open source scripting language. StormScript was created on the belief that a good scripting language can be both powerful and easily readable and learnable.

grade: stable 
confinement: classic

apps:
  stormscript:
    command: bin/stormscript

parts:
  stormscript:
    source: https://github.com/stormprograms/StormScript.git
    source-type: git
    plugin: cmake
