name: stormscript # you probably want to 'snapcraft register <name>'
version: 'v0.1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: StormScript is an easy to use, open-source scripting language  # 79 char long summary
description: |
  StormScript is an open source scripting language. StormScript was created on the belief that a good scripting language can be both powerful and easily readable and learnable.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  stormscript:
    command: bin/stormscript

plugs:
  home:

parts:
  stormscript:
    # See 'snapcraft plugins'
    source: https://github.com/stormprograms/StormScript.git
    source-type: git
    plugin: cmake
