name: C/C++ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        cd scripts;
        ./runtests.sh
        
      
  build_win:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: cmake .  -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
    - name: Make
      run: mingw32-make
